#!/usr/bin/env python3
"""Añadir metadatos YAML v1.0 a fragmentos (.txt) en ./fragments

Especificación: YAML v1.0 (ver PROTOCOLO)

Comportamiento:
 - Modo preview (dry-run) por defecto. Use --apply para escribir cambios.
 - Si el archivo ya contiene un bloque YAML (comienza con '---'), se salta.
 - MESSAGE_ID: detecta dígitos en el nombre del archivo o genera incremental.
 - SESSION_ID y ORIGEN son parámetros configurables (--session, --origen).
 - MESSAGE_HASH: SHA1 corto (10 hex) calculado sobre el contenido del fragmento.
 - FRAGMENT.INDEX y FRAGMENT.TOTAL: INDEX es posición en el conjunto procesado, TOTAL es el total global de fragmentos en la carpeta.
"""

import argparse
from pathlib import Path
import re
import datetime
import hashlib
import sys
import tarfile
import time
import os


def has_yaml_block(content: str) -> bool:
    return content.lstrip().startswith('---')


def extract_message_id_from_name(name: str):
    m = re.search(r"(\d{1,6})", name)
    if m:
        try:
            return int(m.group(1))
        except ValueError:
            return None
    return None


def collect_existing_ids(files):
    ids = []
    for f in files:
        n = extract_message_id_from_name(f.name)
        if n is not None:
            ids.append(n)
    return ids


def build_yaml_block(message_id, session_id, created_at, origen, tags, message_hash, index, total, tema, notes):
    lines = [
        '---',
        f'MESSAGE_ID: "{str(message_id)}"',
        f'SESSION_ID: "{session_id}"',
        '',
        f'CREATED_AT: "{created_at}"',
        f'ORIGEN: "{origen}"',
        '',
        'TAGS:',
    ]
    for t in tags:
        lines.append(f'  - "{t}"')
    lines += [
        '',
        f'MESSAGE_HASH: "{message_hash}"',
        '',
        'FRAGMENT:',
        f'  INDEX: {index}',
        f'  TOTAL: {total}',
        f'  TEMA: "{tema}"',
        '',
        'NOTES: |',
    ]
    for ln in notes.splitlines() if notes else ['']:
        lines.append(f'  {ln}')
    lines += ['---', '']
    return '\n'.join(lines)


def extract_keywords(text, top=3):
    words = re.findall(r"\b[\wÁÉÍÓÚáéíóúñÑ]{4,}\b", text.lower(), flags=re.UNICODE)
    freqs = {}
    stop = {'de', 'la', 'el', 'que', 'y', 'a', 'en', 'para', 'con', 'por', 'no', 'se', 'los', 'las', 'un', 'una'}
    for w in words:
        if w in stop:
            continue
        freqs[w] = freqs.get(w, 0) + 1
    items = sorted(freqs.items(), key=lambda x: -x[1])
    return [w for w, _ in items[:top]]


def process_file(path: Path, message_id, session_id, origen, index, total, apply=False):
    raw = path.read_text(encoding='utf-8')
    if has_yaml_block(raw):
        return False, f"SKIP (already has YAML): {path.name}"

    sample = raw[:5000]
    tags = extract_keywords(sample, top=3)
    if not tags:
        tags = ['fragmento', 'bitacora']

    created_at = datetime.datetime.now().astimezone().isoformat()

    h = hashlib.sha1()
    h.update(raw.encode('utf-8'))
    message_hash = h.hexdigest()[:10]

    tema = tags[0] if tags else ''
    notes = f'Autogenerated: add_yaml_meta.py on {created_at}'

    yaml = build_yaml_block(message_id, session_id, created_at, origen, tags, message_hash, index, total, tema, notes)
    new = yaml + raw
    if apply:
        path.write_text(new, encoding='utf-8')
        return True, f"APPLIED: {path.name} (MESSAGE_ID: {message_id}; MESSAGE_HASH: {message_hash}; tags: {', '.join(tags)})"
    else:
        return None, {'name': path.name, 'yaml': yaml, 'tags': tags, 'message_id': message_id, 'hash': message_hash}


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--dir', default='fragments')
    p.add_argument('--sample', type=int, default=0, help='Número de archivos a probar (0 = todos en preview)')
    p.add_argument('--apply', action='store_true', help='Aplicar los cambios (escribe archivos)')
    p.add_argument('--session', default='CONVERSACIÓN_1', help='Identificador de sesión')
    p.add_argument('--origen', default='NODO_SEMILLA', help='Valor para ORIGEN en YAML')
    args = p.parse_args()

    base = Path(args.dir)
    if not base.exists() or not base.is_dir():
        print(f"Directorio no encontrado: {base}")
        sys.exit(1)

    def create_backup(src_path: Path) -> str:
        """Crea un tar.gz del directorio src_path en el cwd y devuelve la ruta del archivo creado."""
        ts = time.strftime('%Y%m%d_%H%M%S')
        name = f'fragments_backup_{ts}.tar.gz'
        try:
            with tarfile.open(name, 'w:gz') as tar:
                # add the directory itself, preserve relative path
                tar.add(str(src_path), arcname=str(src_path))
            return name
        except Exception as e:
            print(f"ERROR creando backup: {e}")
            return ''

    all_files = sorted([f for f in base.rglob('*.txt') if f.is_file()], key=lambda x: x.name)
    total = len(all_files)
    if total == 0:
        print('No se encontraron archivos .txt en el directorio especificado.')
        return

    files = all_files
    if args.sample > 0:
        files = files[:args.sample]

    # If applying, create an automatic backup before modifying files
    backup_file = None
    if args.apply:
        print('Creando backup automático antes de aplicar cambios...')
        backup_file = create_backup(base)
        if backup_file:
            try:
                size = os.path.getsize(backup_file)
                print(f'Backup creado: {backup_file} ({size} bytes)')
            except Exception:
                print(f'Backup creado: {backup_file}')
        else:
            print('No se pudo crear backup. Abortando para seguridad.')
            return

    existing_ids = collect_existing_ids(all_files)
    max_existing = max(existing_ids) if existing_ids else 0
    next_id = max_existing + 1

    results = []
    for idx, f in enumerate(files, start=1):
        mid = extract_message_id_from_name(f.name)
        if mid is None:
            mid = next_id
            next_id += 1
        applied, info = process_file(f, mid, args.session, args.origen, index=idx, total=total, apply=args.apply)
        results.append((f.name, applied, info))

    # Present summary
    if args.apply:
        for name, applied, info in results:
            print(info)
        print(f"Total modificados: {sum(1 for _, a, _ in results if a)}")
    else:
        for name, applied, info in results:
            print(f"Preview: {name}")
            print(info['yaml'])
            print(f"Keywords: {', '.join(info['tags'])}\n")
        print('Preview completo. Ejecutá con --apply para escribir YAML en los archivos.')


if __name__ == '__main__':
    main()
