#!/usr/bin/env bash
# Reproducible harness: ejecuta cada adapter en un proceso separado con timeout
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PYTHON=".venv/bin/python"
ADAPTERS=(
  modulo_integrador
  llama_dispatcher_connector
  dispatcher_lite
  msg_sequencer
  msg_builder
  simon_validator
  sala_app
)

mkdir -p data docs
TMP_JSON="data/modules_import_report_detailed.json"
declare -A results

echo "Starting adapters harness..."
for a in "${ADAPTERS[@]}"; do
  echo "- Running adapter: $a"
  # run with timeout of 20s
  outfile="/tmp/neurobit_adapter_${a}_out.json"
  if timeout 20s "$PYTHON" scripts/adapter_runner.py "$a" > "$outfile" 2> "/tmp/neurobit_adapter_${a}_err.log"; then
    # read stdout JSON
    stdout=$(cat "$outfile" )
    results["$a"]="$stdout"
    echo "  -> success"
  else
    # timeout or error
    rc=$?
    err=$(cat "/tmp/neurobit_adapter_${a}_err.log" 2>/dev/null || true)
    results["$a"]="$(jq -n --arg r "{\"status\":\"error\",\"note\":\"adapter failed rc=$rc\",\"stderr\":$ (jq -R -s -c <<<\"$err\") }" '$r')"
    echo "  -> failed/timeout (rc=$rc)"
  fi
done

# Compose final JSON
echo "{ \"timestamp\": $(date +%s), \"results\": {" > "$TMP_JSON"
first=true
for a in "${ADAPTERS[@]}"; do
  if [ "$first" = true ]; then
    first=false
  else
    echo "," >> "$TMP_JSON"
  fi
  echo -n "\"$a\": " >> "$TMP_JSON"
  # ensure value is valid JSON
  echo -n "${results[$a]}" >> "$TMP_JSON"
done
echo " } }" >> "$TMP_JSON"

echo "Wrote report to $TMP_JSON"

# Generate a small Markdown summary
cat > docs/modules_integration_report.md <<'MD'
# Modules Integration Report (generated)

This file was generated by `scripts/run_adapters_test.sh`.

MD
echo "- generated_at: $(date -u)" >> docs/modules_integration_report.md
for a in "${ADAPTERS[@]}"; do
  echo "\n## $a" >> docs/modules_integration_report.md
  echo "See data/modules_import_report_detailed.json for details." >> docs/modules_integration_report.md
done

echo "Done. Report and MD saved."
